#!/usr/bin/env python3
"""Drift guard for the three hand-maintained entrypoint docs.

CLAUDE.md, AGENTS.md and GEMINI.md are parallel entrypoints for three different
runtimes and are NOT generated by scripts/sync_codex_compat.py. Without a check
they drift from .claude/agents/ silently — GEMINI.md and .claude-plugin/plugin.json
both carried stale agent counts before this test existed.

`.claude/rules/claude-md.md` requires: "The Agents table must list every agent in
`.claude/agents/` with its correct purpose."
"""
from __future__ import annotations

import json
import re
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
AGENTS_DIR = REPO_ROOT / ".claude" / "agents"
RULES_DIR = REPO_ROOT / ".claude" / "rules"
CLAUDE_MD = REPO_ROOT / "CLAUDE.md"
PLUGIN_JSON = REPO_ROOT / ".claude-plugin" / "plugin.json"
GEMINI_MD = REPO_ROOT / "GEMINI.md"


def agent_names() -> set[str]:
    return {p.stem for p in AGENTS_DIR.glob("*.md")}


class TestClaudeMd(unittest.TestCase):
    def test_agents_table_lists_every_agent(self):
        text = CLAUDE_MD.read_text(encoding="utf-8")
        missing = sorted(n for n in agent_names() if f"`{n}`" not in text)
        self.assertEqual(
            missing, [], f"CLAUDE.md Agents table is missing: {missing}"
        )

    def test_no_phantom_agents_referenced(self):
        """Every `backtick-name` in the Key Agents table must be a real agent."""
        text = CLAUDE_MD.read_text(encoding="utf-8")
        match = re.search(r"### Key Agents\n(.*?)\n### ", text, re.S)
        self.assertIsNotNone(match, "CLAUDE.md has no '### Key Agents' section")
        known = agent_names()
        phantom = []
        for row in match.group(1).splitlines():
            if not row.startswith("|") or row.startswith("|---") or row.startswith("| Agent"):
                continue
            cell = row.split("|")[1]
            for name in re.findall(r"`([a-z0-9-]+)`", cell):
                if name not in known:
                    phantom.append(name)
        self.assertEqual(
            phantom, [], f"CLAUDE.md references non-existent agents: {phantom}"
        )

    def test_rules_section_lists_every_rule_file(self):
        text = CLAUDE_MD.read_text(encoding="utf-8")
        missing = sorted(
            p.name for p in RULES_DIR.glob("*.md") if f"`{p.stem}.md`" not in text
        )
        self.assertEqual(missing, [], f"CLAUDE.md Rules section is missing: {missing}")

    def test_stays_under_line_budget(self):
        """claude-md.md rule: keep under 400 lines."""
        lines = len(CLAUDE_MD.read_text(encoding="utf-8").splitlines())
        self.assertLess(lines, 400, f"CLAUDE.md is {lines} lines; budget is 400")


class TestAgentCountClaims(unittest.TestCase):
    """Docs that state a headline agent count must state the real one."""

    def test_plugin_json_count(self):
        data = json.loads(PLUGIN_JSON.read_text(encoding="utf-8"))
        match = re.search(r"(\d+)\s+specialized AI agents", data["description"])
        self.assertIsNotNone(
            match, "plugin.json description no longer states an agent count"
        )
        self.assertEqual(
            int(match.group(1)),
            len(agent_names()),
            "plugin.json agent count is stale",
        )

    def test_gemini_md_count(self):
        text = GEMINI_MD.read_text(encoding="utf-8")
        match = re.search(r"Horus contains (\d+) specialized audit workflows", text)
        self.assertIsNotNone(
            match, "GEMINI.md no longer states a workflow count"
        )
        self.assertEqual(
            int(match.group(1)), len(agent_names()), "GEMINI.md agent count is stale"
        )


if __name__ == "__main__":
    unittest.main()
