#!/usr/bin/env python3
"""
Regenerates the 'Report Branches Reference' section in docs/codebase-structure.md.

Scans reports/ for subdirectories, counts .md files, computes the branch name
(mirrors the logic in split-reports.yml), and replaces the block between
<!-- BEGIN REPORT_BRANCHES --> and <!-- END REPORT_BRANCHES -->.
"""

import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
REPORTS_DIR = REPO_ROOT / "reports"
STRUCTURE_FILE = REPO_ROOT / "docs" / "codebase-structure.md"
REPO_OWNER = "calc1f4r"
REPO_NAME = "Horus"
REPO_REF = "hunt-cards"

BEGIN_MARKER = "<!-- BEGIN REPORT_BRANCHES — auto-generated by update-codebase-structure.yml, do not edit manually -->"
END_MARKER = "<!-- END REPORT_BRANCHES -->"


def collect_branches():
    """Return sorted list of (branch_name, source_dir, md_count)."""
    entries = []
    for child in sorted(REPORTS_DIR.iterdir()):
        if not child.is_dir():
            continue
        folder = child.name
        # Mirror split-reports.yml: strip _findings suffix
        clean = re.sub(r"_findings$", "", folder)
        branch = f"reports/{clean}"
        md_count = sum(1 for f in child.iterdir() if f.suffix == ".md")
        entries.append((branch, f"reports/{folder}/", md_count))
    return entries


def build_section(entries):
    """Build the markdown table block."""
    total_reports = sum(c for _, _, c in entries)
    lines = [
        "",
        "Each branch below contains **only** the reports for that category.",
        "",
        "**Fetch a single file** (replace `<CATEGORY>` and `<FILE>`):",
        "```bash",
        "mkdir -p reports/<CATEGORY>",
        f'gh api "repos/{REPO_OWNER}/{REPO_NAME}/contents/reports/<CATEGORY>/<FILE>?ref={REPO_REF}" --jq \'.content\' | base64 -d > reports/<CATEGORY>/<FILE>',
        "```",
        "",
        "**Clone entire category** into `reports/`:",
        "```bash",
        f"gh repo clone {REPO_OWNER}/{REPO_NAME} reports/<CATEGORY> -- --branch reports/<BRANCH> --single-branch --depth 1",
        "```",
        "",
        "| Branch | Source Directory (CATEGORY) | Reports |",
        "|--------|---------------------------|---------|",
    ]
    for branch, src, count in entries:
        folder = src.rstrip("/").split("/")[-1]
        lines.append(f"| `{branch}` | `{folder}` | {count} |")

    lines.append("")
    lines.append(f"**Total: {len(entries)} branches · {total_reports:,} reports**")
    lines.append("")
    lines.append("> Report counts and branches are auto-updated by `update-codebase-structure.yml` on every push that modifies `reports/`.")
    lines.append("")
    return "\n".join(lines)


def main():
    if not STRUCTURE_FILE.exists():
        print(f"ERROR: {STRUCTURE_FILE} not found", file=sys.stderr)
        sys.exit(1)

    content = STRUCTURE_FILE.read_text()

    begin_idx = content.find(BEGIN_MARKER)
    end_idx = content.find(END_MARKER)
    if begin_idx == -1 or end_idx == -1:
        print("ERROR: Could not find BEGIN/END REPORT_BRANCHES markers in docs/codebase-structure.md", file=sys.stderr)
        sys.exit(1)

    entries = collect_branches()
    section = build_section(entries)

    new_content = (
        content[: begin_idx + len(BEGIN_MARKER)]
        + section
        + content[end_idx:]
    )

    if new_content != content:
        STRUCTURE_FILE.write_text(new_content)
        print(f"Updated docs/codebase-structure.md — {len(entries)} branches, {sum(c for _, _, c in entries):,} reports")
    else:
        print("docs/codebase-structure.md is already up to date")


if __name__ == "__main__":
    main()
